version: '3'
services:
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    container_name: mysql_db

  phpmyadmin_db:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    links:
      - mysql_db:db
    container_name: phpmyadmin_db